trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo "Pulling Flogo Docker image from public registry..."
    docker pull flogo/flogo-docker
  displayName: 'Pull Flogo Docker Image'

- script: |
    echo "Running Flogo Docker container..."
    docker run -d -p 3303:3303 flogo/flogo-docker eula-accept
  displayName: 'Run Flogo Docker Container'
