trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    # Check if Go is installed
    if ! command -v go &> /dev/null; then
        echo "Go is not installed. Installing Go..."
        sudo apt update
        sudo apt install -y golang-go
    fi

    # Install Flogo CLI
    go install github.com/project-flogo/cli/...@latest

    # Ensure the Flogo CLI is in the PATH
    export PATH=$PATH:$(go env GOPATH)/bin

    # Check the version to confirm installation
    flogo --version
  displayName: 'Install Flogo CLI'

- script: |
    export GOPATH=$HOME/go
    export PATH=$PATH:$GOPATH/bin

    # Run flogo build on your flogo.json
    flogo build -f flogo.json
    echo "Contents of bin directory after build:"
    ls -ltra bin
  displayName: 'Flogo Build'

- script: |
    echo "Running Flogo binary..."
    cd bin
    chmod +x *   # make sure the binary is executable
    ./$(ls | head -n 1) &
    sleep 10     # let it run for a bit (adjust as needed)
  displayName: 'Flogo Run'
