trigger:
- main   # or whatever branch you want

pool:
  vmImage: 'ubuntu-latest'

steps:
# Install Go (needed for Flogo)
- task: UseGo@0
  inputs:
    version: '1.20.x'   # choose a Go version supported by Flogo

# Install Flogo CLI
- script: |
    curl -sL https://github.com/TIBCOSoftware/flogo-cli/releases/download/v0.5.8/flogo-0.5.8-linux-amd64.tar.gz -o flogo.tar.gz
    tar -xzf flogo.tar.gz
    sudo mv flogo /usr/local/bin/
    flogo version
  displayName: 'Install Flogo CLI'

# Run Flogo Build
- script: |
    flogo build -f flogo.json
  displayName: 'Build Flogo App'

# (Optional) Publish the generated binary as a pipeline artifact
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'bin'
    ArtifactName: 'flogo-binaries'
    publishLocation: 'Container'
