trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    go install github.com/project-flogo/cli/...@latest
    chmod +x build.sh
    ./build.sh
  displayName: 'Build Flogo Project'

- publish: /path/to/artifacts/
  artifact: flogo-executable
