trigger:
- main   # or your branch

pool:
  vmImage: 'ubuntu-latest'

steps:
# Install Go
- script: |
    GO_VERSION=1.20.14
    curl -sL https://golang.org/dl/go${GO_VERSION}.linux-amd64.tar.gz -o go.tar.gz
    sudo tar -C /usr/local -xzf go.tar.gz
    echo "##vso[task.prependpath]/usr/local/go/bin"
    go version
  displayName: 'Install Go'

# Install Flogo CLI
- script: |
    ls -ltra
    curl -sL https://github.com/project-flogo/cli/archive/refs/tags/v0.12.0.tar.gz -o flogo.tar.gz
    tar -xzf flogo.tar.gz
    ls -ltra
    echo "blaat"
    sudo mv cli-0.12.0 /usr/local/bin/flogo
    flogo version
  displayName: 'Install Flogo CLI'

# Run Flogo Build
- script: |
    flogo build -f flogo.json
  displayName: 'Build Flogo App'

# # (Optional) Publish build artifacts
# - task: PublishBuildArtifacts@1
#   inputs:
#     PathtoPublish: 'bin'
#     ArtifactName: 'flogo-binaries'
#     publishLocation: 'Container'
